//copyright(c)2026 Cyli123
#ifndef CAMERA_H_INCLUDED
#define CAMERA_H_INCLUDED
#define FIRSTPERSON CAMERA_FIRST_PERSON
#define THIRDPERSON CAMERA_THIRD_PERSON
#define ORBITCAMERA CAMERA_ORBITAL
#define EXPLORERCAMERA CAMERA_FREE
#define FLY_CAMERA CAMERA_FREE



void setCameraStyle(int mode);

#endif // CAMERA_H_INCLUDED
